### PR TITLE
fix: include security and component changes in markdown/HTML changelog

### LINKED ISSUE #814: Markdown and HTML output are now showing security / components changes
**Describe the bug**
Markdown and HTML formats only print changes to API endpoints, not to `security` or `components`.

**To Reproduce**
1. The command-line, for example: `oasdiff breaking spec1.yaml spec2.yaml --fail-on ERR`
2. Spec 1:
```
{"info":{"title":"Healthcheck API","version":"v1"},"openapi":"3.0.0","paths":{"/healthcheck":{"get":{"operationId":"getHealthcheck","responses":{"204":{"description":""}},"summary":"Healthcheck","tags":["Healthcheck"]}}},"servers":[{"url":"/healthcheck-api/v1"}]}
```
3. Spec 2
```
{"openapi":"3.0.0","info":{"title":"Healthcheck API","version":"v1"},"servers":[{"url":"/healthcheck-api/v1"}],"paths":{"/healthcheck":{"get":{"tags":["Healthcheck"],"summary":"Healthcheck","operationId":"getHealthcheck","responses":{"204":{"description":""}}}}},"components":{"securitySchemes":{"ApiKeyAuth":{"type":"apiKey","name":"X-API-Key","in":"header"}}},"security":[{"ApiKeyAuth":[]}]}
```
4. Markdown output
```
# API Changelog v1 vs. v1

````
5. json output
```
[
  {
    "id": "api-global-security-added",
    "text": "the security scheme 'ApiKeyAuth' was added to the API",
    "level": 1,
    "section": "security"
  },
  {
    "id": "api-security-component-added",
    "text": "the component security scheme 'ApiKeyAuth' was added",
    "level": 1,
    "section": "components"
  }
]

```
**Expected behavior**

Markdown output should show the same diff as the json output

**Desktop (please complete the following information):**
 - OS: `docker run docker tufin/oasdiff ...`

### PR DESCRIPTION
**Pull request by plaflamme**
`GroupChanges()` only handled `ApiChange` via a type switch, silently dropping `SecurityChange` and `ComponentChange`. This caused markdown and HTML formatters to produce empty output when all changes were non-API.

## Changes

**Core fix:**
- Handle `SecurityChange` and `ComponentChange` in `GroupChanges()` by grouping them under a `Section` key
- Rename `Endpoint`/`ChangesByEndpoint` to `ChangeGroup`/`ChangesByGroup` to reflect that grouping now covers all change types
- Add deprecated `APIChanges()` alias on `TemplateData` for backward compatibility with custom templates

**Template improvements:**
- Add `pathGroups`, `sectionGroups`, and `capitalize` template functions (shared by HTML and Markup formatters) for deterministic sorted output
- Update `changelog.html`: path-based changes appear under an "API Changes" header; section groups (security, components) get styled `.section-title` headers; "No changes" shown when changelog is empty
- Update `changelog.md`: same structure as HTML with capitalized section headers and "No changes" fallback
- Add `MarkupTemplateFuncs()` and wire it into the Markup formatter so custom markdown templates have access to the same functions

**Documentation:**
- Add `docs/CHANGELOG-TEMPLATE.md` with full reference for template data fields and functions
- Update `docs/USAGE_EXAMPLES.md` to link to the new doc
- Update `examples/changelog.html` and `examples/changelog.md` to reflect new output structure
- Update `examples/custom-changelog-template.md` to use the new template functions

Fixes #814

### CODE REVIEW

File: formatters/changes_by_group.go [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+	result := ChangesByGroup{}
+
+	for _, change := range changes {
+		var group ChangeGroup
+
+		switch change.(type) {
+		case checker.ApiChange:
+			group = ChangeGroup{Path: change.GetPath(), Operation: change.GetOperation()}
+		default:
+			group = ChangeGroup{Path: change.GetSection()}
```
Comment (reuvenharrison) [inline formatters/changes_by_group.go]: Better to avoid reusing Path for Section

**Comment by reuvenharrison** [comment]
Good catch. Good fix. Just address the comment above please.

**Comment by plaflamme** [comment]
@reuvenharrison Sorry, which comment exactly? The codecov report is all green.

**Comment by reuvenharrison** [comment]
https://github.com/oasdiff/oasdiff/pull/815#discussion_r2951213296

**Comment by plaflamme** [comment]
@reuvenharrison I can't see that comment for some reason. Perhaps the PR review hasn't been submitted yet?

**Review by reuvenharrison — CHANGES_REQUESTED** [review]

File: formatters/changes_by_group.go (hunk 1 above)
Comment (plaflamme) [reply formatters/changes_by_group.go]: Fixed in https://github.com/oasdiff/oasdiff/pull/815/commits/92b804fec73a186fe6c748eefc700185e035ccd4
