### PR TITLE
response-media-type-changed

### LINKED ISSUE #686: `ContentType: application/json` -> `application/problem+json` is safe but is show as breaking
**Describe the bug**
Narrowing of mime type should be handled as safe.

There is an official list at https://www.iana.org/assignments/media-types/media-types.xhtml#application

**To Reproduce**
1. change ContentType header from  `application/json` to `application/problem+json`.

**Expected behavior**
Change should be shown as safe.

**Additional resources**
https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types

### PR DESCRIPTION
**Pull request by reuvenharrison**
This PR fixes https://github.com/oasdiff/oasdiff/issues/686 by adding the ability to compare media-types and report response-media-type-changed when the new media type is contained in the original one.

For example:
- `application/atom+xml` is contained in `application/xml`
- `application/problem+json` is contained in `application/json`
- `image/svg+xml` is contained in `image/xml`

Note:
- The part after the `+` is called a suffix as explained here: https://en.wikipedia.org/wiki/Media_type#Suffix
- This PR won't support multiple suffixes: https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-01.html

### CODE REVIEW

File: diff/content_diff.go [hunk 1]
```diff
@@ -49,28 +49,94 @@ func getContentDiff(config *Config, state *state, content1, content2 openapi3.Co
...
 		}
 	}
 
-	return result, nil
+	// 3. Iteratively find equivalent pairs from initial Added/Deleted lists
+	finalAdded := make(utils.StringList, 0, len(initialResult.MediaTypeAdded))
+	finalModified := initialResult.MediaTypeModified // Start with exact matches
+
+	for _, addedName := range initialResult.MediaTypeAdded {
+		foundEquivalentDeleted := false
```
Comment (jguddas) [inline diff/content_diff.go:87]: If the count of added and deleted is both 1, we could also consider that as a change, even if the content also changed 🤔

Comment (reuvenharrison) [reply diff/content_diff.go:87]: I understand the idea but I think it could lead to errors.
For example, if media-type changed from application/xml to application/json.
